ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
    }
    application {
        modules = [ com.terabyte.angamessenger.auth.ApplicationKt.module ]
    }
}

jwt {
    secret = ${?JWT_SECRET}
    accessTimeToLive = "15m"
    refreshTimeToLive = "7d"
}

database {
    url = ${?DB_URL}
    driver = "org.postgresql.Driver"
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
}
